root __INSTALL_DIR__/src;

# Default clean URL routing
location / {
    try_files $uri @clean_url;
}

location @clean_url {
    rewrite ^(.*)$ /index.php last;
}

location ~ ^/index\.php(/|$) {
    include fastcgi_params;

    fastcgi_read_timeout 1800;

    fastcgi_split_path_info ^(.+\.php)(/.+)$;

    # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $realpath_root;

    #fastcgi_cache app;
    #fastcgi_cache_use_stale timeout updating;

    fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
    internal;
}

# Set up caching for static assets.
location /static {
    add_header Access-Control-Allow-Origin *;
}

location /static/uploads {
    rewrite ^(.+)\.(?:\w+)\.(js|css|png|jpg|webp)$ $1.$2 last;
    alias __INSTALL_DIR__/storage/uploads;
    try_files $uri =404;
}

location /static/vite_dist {
    expires 365d;
}
location /static/icons {
    expires 365d;
}
location /static/img {
    expires 7d;
}
location /favicon.ico {
    add_header Access-Control-Allow-Origin *;
    expires 365d;
}

# Return 404 for all other php files not matching the front controller
location ~ \.php$ {
    return 404;
}

# deny access to .htaccess files, if Apache's document root
# concurs with nginx's one
location ~ /\.ht {
    deny all;
}

# Serve a static version of the nowplaying data for non-PHP-blocking delivery.
location /api/nowplaying_static {
    expires 10s;
    add_header Access-Control-Allow-Origin *;

    alias __INSTALL_DIR__/www_tmp/nowplaying;
    try_files $uri =404;
}

# Websocket/SSE Now Playing Updates
location ~ ^/api/live/nowplaying/(\w+)$ {
    include proxy_params;
    proxy_pass http://centrifugo/connection/uni_$1?$args;
}

# Internal handlers used by the application to perform X-Accel-redirect's for higher performance.
location /internal/backups/ {
    internal;
    add_header Access-Control-Allow-Origin "$upstream_http_access_control_allow_origin";
    alias __INSTALL_DIR__/backups/;
}

location /internal/storage/ {
    internal;
    add_header Access-Control-Allow-Origin "$upstream_http_access_control_allow_origin";
    alias __INSTALL_DIR__/storage/;
}

location /internal/stations/ {
    internal;
    add_header Access-Control-Allow-Origin "$upstream_http_access_control_allow_origin";
    alias __INSTALL_DIR__/stations/;
}


