#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/src"

chown -R $app:www-data "$install_dir"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Building $app... this will take some time..."

pushd $install_dir/src

    composer_workdir=$install_dir/src
    mv ../composer.phar ./
    ynh_composer_exec install --no-dev --no-autoloader 
    ynh_composer_exec dump-autoload --optimize --classmap-authoritative

    ynh_exec_as_app npm ci
    ynh_exec_as_app npm run build

popd


#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx


#=================================================
ynh_script_progression "Configuring $app..."
#=================================================

redis_db=$(ynh_redis_get_free_db)

ynh_config_add --template="azuracast.env" --destination="$install_dir/src/azuracast.env"

for DIR in backups stations www_tmp storage
do
    ln -s $data_dir/$DIR $install_dir/$DIR
done

#=================================================
ynh_script_progression "Initializing $app..."
#=================================================

pushd $install_dir
    php8.4 src/backend/bin/console migrations:migrate --no-interaction
    php8.4 src/backend/bin/console azuracast:setup --init --no-interaction
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
