#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/src"

chown -R $app:www-data "$install_dir"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Building $app... this will take some time..."

pushd $install_dir/src

    composer_workdir=$install_dir/src
    mv ../composer.phar ./
    ynh_composer_exec install --no-dev --no-autoloader 
    ynh_composer_exec dump-autoload --optimize --classmap-authoritative

    ynh_exec_as_app npm ci
    ynh_exec_as_app npm run build

popd


#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx


#=================================================
ynh_script_progression "Configuring $app..."
#=================================================

redis_db=$(ynh_redis_get_free_db)

ynh_config_add --template="azuracast.env" --destination="$install_dir/src/azuracast.env"

for DIR in backups stations www_tmp storage
do
    ln -s $install_dir/$DIR $data_dir/$DIR
done

#=================================================
ynh_script_progression "Initializing $app..."
#=================================================

pushd $install_dir
    php8.4 src/backend/bin/console azuracast:setup --init --no-interaction || true  # First time it will crash saying `/var/www/azuracast/www_tmp` is not writable yet if you rerun it *is* able to write in it ...
    php8.4 src/backend/bin/console azuracast:setup --init --no-interaction
    php8.4 src/backend/bin/console migrations:migrate --no-interaction <<< "yes"
popd

# Initialize the mysql db
# Fucking archive doesnt shit the goddamn util/docker folder because of https://github.com/AzuraCast/AzuraCast/blob/main/.gitattributes#L21
# so we have to fetch this shit manually
#curl -s https://raw.githubusercontent.com/AzuraCast/AzuraCast/refs/tags/$(ynh_app_upstream_version)/util/docker/mariadb/mariadb/db.sql > init_db.sql
# For some reason these 2 lines from the dump trigger : ERROR at line 1 in file: 'init_db.sql': Unknown command '\-'. .....
#sed -i '/.*enable the sandbox mode.*/d' init_db.sql
#mysql -B $app < init_db.sql



# FIXME / TODO
# For some reason the app complained about Field '<some file>' doesn't have a default value
# ... a savage hack is to remove the STRICT_TRANS_TABLES from the sql mode ... though I have no clue if that's legit, that sounds pretty brutal
# cf: SHOW VARIABLES LIKE 'sql_mode';
# SET GLOBAL sql_mode='ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
