#!/bin/bash
### App file generated with YoloGen, the Yunohost app generator, version .

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/src"

pushd $install_dir
    mkdir -p stations backups storage/uploads storage/shoutcast2 storage/stereo_tool storage/rsas storage/geoip storage/sftpgo storage/acm
popd

chown -R $app:www-data "$install_dir"


#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir/src

    composer_workdir=$install_dir/src
    ynh_composer_exec install --no-dev --no-autoloader 
    ynh_composer_exec dump-autoload --optimize --classmap-authoritative

    ynh_exec_as_app npm ci

popd

#=================================================
# ADD A CONFIGURATION
#=================================================
#ynh_script_progression "Adding app's configuration file..."

#ynh_config_add --template="" --destination="$install_dir/"
#
#chmod 400 "$install_dir/"
#chown "$app:$app" "$install_dir/"



# Initialize the mysql db

mysql -B $app < $install_dir/src/util/docker/mariadb/mariadb/db.sql

# FIXME / TODO
# For some reason the app complained about Field '<some file>' doesn't have a default value
# ... a savage hack is to remove the STRICT_TRANS_TABLES from the sql mode ... though I have no clue if that's legit, that sounds pretty brutal
# cf: SHOW VARIABLES LIKE 'sql_mode';
# SET GLOBAL sql_mode='ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# FINALIZE APP INSTALL WITH CURL
#=================================================
ynh_script_progression "Finalizing installation..."

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
